apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vk3u82gcw-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vk3u82gcw-java-quarkus-gitops